[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql"]

[phases.build]
cmds = ["mkdir -p /app/public/uploads"]

[start]
cmd = "cd public && php -S 0.0.0.0:${PORT:-8080}"
